#%RAML 1.0 ResourceType

get:
  description: This is used to fetch <<resourcePathName | !singularize>> details
  responses:
    200:
      body:
        application/json:
          type: <<customerDetails>>