#%RAML 1.0 DataType

example: !include ../examples/customerDetails.raml

properties:
  cId:
    type: integer
  name:
    type: string
  contact:
    type: string
  email:
    type: string
  age:
    type: integer
  city:
    type: string
  designation:
    type: string
  salary:
    type: integer
  loanAmount:
    type: integer